cmake_minimum_required(VERSION 4.0)
project(practice)

add_subdirectory(counter)
add_subdirectory(spacex)
add_subdirectory(spsc)
add_subdirectory(inline)
add_subdirectory(cstuff)
add_subdirectory(memove)
add_subdirectory(bits)
add_subdirectory(spi-temp-driver)
add_subdirectory(heater)
add_subdirectory(cring)
add_subdirectory(mpmc)
add_subdirectory(water)
add_subdirectory(barrier)
add_subdirectory(barrier2)
add_subdirectory(packet)
add_subdirectory(mpmc_timeout)
add_subdirectory(debug_prac)
add_subdirectory(dsp)
